# Generated by Django 2.2 on 2020-11-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.ResumeTemplate'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
